using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Shantiw.Data.Schema
{
    public static class SchemaVocab
    {
        public const string Type = "Type";

        public const string TableName = "TableName";
        public const string ColumnName = "ColumnName";
        public const string ForeignKeyName = "ForeignKeyName";

        public const string Name = "Name";
        public const string ReadOnly = "ReadOnly";

        public const string Schema = "Schema";
        public const string Model = "Model";
        public const string CreatedAt = "CreatedAt";

        public const string EntityType = "EntityType";
        public const string EntitySetName = "EntitySetName";

        public const string Property = "Property";

        public const string Nullable = "Nullable";
        public const string AutoGenerated = "AutoGenerated";
        public const string SequenceName = "SequenceName";
        public const string DefaultValue = "DefaultValue";
        public const string MaxLength = "MaxLength";
        public const string ConcurrencyCheck = "ConcurrencyCheck";

        public const string NavigationProperty = "NavigationProperty";
        public const string Relationship = "Relationship";

        public const string Key = "Key";
        public const string Unique = "UniqueConstraint";
        public const string PropertyRef = "PropertyRef";

        public const string Association = "Association";
        public const string End = "End";
        public const string Role = "Role";
        public const string FromRole = "FromRole";
        public const string ToRole = "ToRole";
        public const string ReferentialConstraint = "ReferentialConstraint";
        public const string Principal = "Principal";
        public const string Dependent = "Dependent";
        public const string Order = "Order";

        public const string Annotation = "Annotation";
    }

    public static class Multiplicity
    {
        public const string ZeroOne = "0..1";
        public const string One = "1";
        public const string Many = "*";
    }
}
